--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat
spec: 
  selector: 
    matchLabels: 
      run: tomcat
  replicas: 2
  template: 
    metadata: 
      labels: 
        run: tomcat
    spec: 
      containers: 
      - 
        image: "vivekbangare2492/tomcat:1"
        name: tomcat
        ports: 
        - containerPort: 80